disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - type_name
  - line_length

included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - Sources
  - Tests

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - README.md

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)