coverage:
  status:
    project:
      default:
        # basic
        target: 60%
        threshold: 0%
        paths: 
          - "Sources"
    patch:
      default:
        # basic
        target: 85%
        threshold: 0%
        paths: 
          - "Sources"
