name: Publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run-tests-workflow:
    if: ${{ vars.PUBLIC_REMOTE_URL != '' }}
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: run-tests-workflow
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        timeout-minutes: 2

      - name: Run publish script
        env:
          PUBLIC_REMOTE_URL: ${{ vars.PUBLIC_REMOTE_URL }}
          GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }} # TBD: write embrace-apple-sdk - going away after internal/public repo merge
        run: |
          bin/publish
