name: Publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run-tests-workflow:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: run-tests-workflow
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Run publish script
        env:
          PUBLIC_REMOTE_URL: ${{ vars.PUBLIC_REMOTE_URL }}
        run: |
          git config --global user.name "embrace-ci"
          git config --global user.email "embrace-ci@users.noreply.github.com"
          git config --global url."https://${{ secrets.CD_GITHUB_USER }}:${{ secrets.CD_GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

          bin/publish
