
name: Run Swift Tests

on:
  pull_request: {}
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  run-tests:
    timeout-minutes: 20
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          xcodebuild -version

      - uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Cache Swift Package Dependencies
        uses: actions/cache@v2
        with:
          path: .build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-xctest-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xctest-

      - name: Run Tests
        run: bin/test | xcpretty && exit ${PIPESTATUS[0]}
        timeout-minutes: 30

      - uses: embrace-io/xcresulttool@v1
        with:
          path: .build/test/output.xcresult
          title: "Test Results"
          show-passed-tests: true
          show-code-coverage: true
          upload-bundles: true
        if: success() || failure()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: unittests
          fail_ci_if_error: true
          xcode: true
          xcode_archive_path: .build/test/output.xcresult
