name: Run Danger

on:
  pull_request:
    branches:
      - main
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: macos-13
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          xcodebuild -version

      - name: Install Danger Swift
        run: |
          brew install danger/tap/danger-swift
          danger-swift --version

      - name: Run Danger
        run: danger-swift ci
